import { Hidden } from '@material-ui/core';
import { makeStyles } from '@material-ui/core/styles';
import Plus from '../../images/plus.svg';
import Background from '../../images/intro.png';

export default makeStyles((theme) => ({
    btnshowmore:{
        color: 'white',
        backgroundColor: '#3d88e4',
        fontFamily: 'Barlow Condensed, sans-serif',
        textTransform: 'capitalize',
        width: 160,
        height: 38,
        borderRadius: 8,
        marginTop: 5,
     
        [theme.breakpoints.down("sm")]:{
            marginTop: 15,
          },
    },
    text:{
        fontFamily: 'Barlow Condensed, sans-serif',
        [theme.breakpoints.down("sm")]:{
           fontSize:  '1.5rem',
         },
    },
    firsttext:{
        fontFamily: 'Barlow Condensed, sans-serif',
        [theme.breakpoints.down("sm")]:{
            marginTop:300,
            fontSize:  '1.5rem',
         },
    },
    mobiletext:{
        display: 'none',
        [theme.breakpoints.down("sm")]:{
            display: 'flex',
            fontFamily: 'Barlow Condensed, sans-serif',
            color: '#3d88e4',
            fontSize: '3rem',
            textAlign: 'center',
          },
    },
    textschedule:{
        fontFamily: 'Barlow Condensed, sans-serif',
        [theme.breakpoints.down("sm")]:{
            textAlign: 'center',
            width: '100%',
            fontSize:  '1.5rem',
         },
    },
    textp:{
        fontFamily: 'Barlow Condensed, sans-serif',
        marginTop: 15,
        [theme.breakpoints.down("sm")]:{
            fontSize:  '0.7rem',
            marginTop: 15,
          },
    },
    textpextra:{
        fontFamily: 'Barlow Condensed, sans-serif',
        marginTop: 15,
        [theme.breakpoints.down("sm")]:{
            fontSize:  '0.7rem',
            marginTop: 15,
          },
    },
    textpstep:{
        fontFamily: 'Barlow Condensed, sans-serif',
        marginTop: 40,
        height: 10, 
    },
    textpschedule:{
        fontFamily: 'Barlow Condensed, sans-serif',
        marginTop: -40,
        [theme.breakpoints.down("sm")]:{
            marginTop: -18,
         },
    },
    pricetext:{
        fontFamily: 'Barlow Condensed, sans-serif',
        textAlign: 'center',
        height: 35,
        paddingTop: 30,
        
    },
    priceboxtexttitle:{
        fontFamily: 'Barlow Condensed, sans-serif',
        fontSize: 15,
        textAlign: 'center',
        height: 25,
        marginTop: -35,
        color: '#89888e',
    },
    pricesubtitletext:{
        fontFamily: 'Barlow Condensed, sans-serif',
        textAlign: 'center',
        paddingTop: 30,
    },
    pricecountainer:{
        width: '100%',
        height: 'auto',  
    },
    countainer:{
        width: '45%',
        height: '40%',
        paddingTop:170,
        paddingLeft:120,
        display: ' inline-block',
        [theme.breakpoints.down("sm")]:{
            display: ' block',
            width: '80%',
            height: '26%',
            paddingTop:170,
            paddingLeft:55,
         },
    },
    countainer2:{
        width: '45%',
        height: '40%',
        paddingTop:170,
        paddingLeft:120,
        display: ' inline-block',
    },
    countainerservices:{
        width: '45%',
        height: '40%',
        paddingTop:170,
        paddingLeft:120,
        display: ' inline-block',
        [theme.breakpoints.down("sm")]:{
            display: ' block',
            width: '80%',
            height: '26%',
            paddingTop:170,
            paddingLeft:55,
         },
    },
    countainersideimg:{
        display: ' inline-block',
        height: '65%',
        float: 'left',
        marginTop: 60,
        [theme.breakpoints.down("sm")]:{
            display: ' block',
         },
    },
    countainersideimgchisiamo:{
        display: ' inline-block',
        height: '65%',
        float: 'left',
        marginTop: 60,
        [theme.breakpoints.down("sm")]:{
            display: ' block',
            marginTop: 120,
            width: '100%',
            height: '50%',
            float: 'none',
         },
    },
    countainersideimgstep:{
        display: ' inline-block',
        height: '65%',
        float: 'left',
        marginTop: 60,
        [theme.breakpoints.down("sm")]:{
            display: ' flex',
            marginTop: 180,
            width: '100%',
            height: '50%',
            float: 'none',
            justifyContent: 'center',
            alignSelf: 'center',
            textAlign: 'center',
         },
    },
    countainersideimgorari:{
        display: ' inline-block',
        height: '65%',
        float: 'left',
        marginTop: 60,
        [theme.breakpoints.down("sm")]:{
            display: ' flex',
            width: '100%',
            height: '50%',
            justifyContent: 'center',
            alignSelf: 'center',
            float: 'none',
         },
    },
    countainersideimg2:{
        display: ' inline-block',
        height: '65%',
        float: 'right',
        marginTop: 60,
        paddingRight:120,
    },
    countainersideimgservices:{
        display: ' inline-block',
        height: '65%',
        float: 'right',
        marginTop: 60,
        paddingRight:120,
        [theme.breakpoints.down("sm")]:{
            justifyContent: 'center',
            alignSelf: 'center',
            width: '100%',
            float: 'none',  
            paddingRight:0,
            marginTop:105,
         },
    },
    sideimg:{
        width: '100%',
        height: '95%',
        marginTop: 50,
        paddingLeft: 150,
    },
    sideimgchisiamo:{
        width: '100%',
        height: '95%',
        marginTop: 50,
        paddingLeft: 150,
        [theme.breakpoints.down("sm")]:{
            width: '90%',
            height: '85%',
            marginTop: 50,
            justifyContent: 'center',
            alignSelf: 'center',
            display: 'block',
            paddingLeft: 0,
            marginLeft: 20,
         },
    },
    sideimgstep:{
        width: '100%',
        height: '95%',
        marginTop: 50,
        paddingLeft: 150,
        [theme.breakpoints.down("sm")]:{
            width: '95%',
            height: '90%',
            marginTop: 50,
            justifyContent: 'center',
            alignSelf: 'center',
            display: 'block',
            paddingLeft: 0,
         },
    },
    sideimgorari:{
        width: '100%',
        height: '95%',
        marginTop: 50,
        paddingLeft: 150,
        [theme.breakpoints.down("sm")]:{
            width: '90%',
            height: '85%',
            marginTop: 50,
            justifyContent: 'center',
            alignSelf: 'center',
            display: 'block',
            paddingLeft: 0,
         },
    },
    pricebox:{
        backgroundColor:'#89888e28',
        width: '12%',
        height: 140,
        borderRadius: 8,
        margin: 8,
        textAlign: 'center',
        verticalAlign: 'middle',
        alignItems: 'center',
        justifyContent:'center',
        [theme.breakpoints.down("sm")]:{
            width: 120,
         },
    },
    priceboxstep:{
        backgroundColor:'#89888e28',
        width: '12%',
        height: 140,
        width: 120,
        borderRadius: 8,
        margin: 8,
        textAlign: 'center',
        verticalAlign: 'middle',
        alignItems: 'center',
        justifyContent:'center',
    },
    priceboxtext:{
        fontFamily: 'Barlow Condensed, sans-serif',
        alignSelf:'center',
        textAlign: 'center',
        height: 25,
        verticalAlign: 'middle',
        color: '#89888e',
    },
    row:{
        display: 'flex',
        flexDirection: 'row',
        marginLeft: 120,
        marginRight: 120,
        marginTop: 75,
        justifyContent:'center',
        [theme.breakpoints.down("sm")]:{
            marginLeft: 0,
            marginRight: 0,
            display:'grid',
            gridTemplateColumns: '150px  140px',
         },
    },
   
    rowservice:{
        display: 'flex',
        flexDirection: 'row',
        height: 250,
        paddingTop: 75,
        justifyContent:'center',
    },
    row2:{
        display: 'flex',
        flexDirection: 'row',
        marginLeft: 120,
        marginRight: 120,
        marginTop: 8,
        justifyContent:'center',
        [theme.breakpoints.down("sm")]:{
            marginLeft: 0,
            marginRight: 0,
            display:'grid',
            gridTemplateColumns: '150px  140px',
         },
    },
    rowservice2:{
        display: 'flex',
        flexDirection: 'row',
        marginTop: 8,
        justifyContent:'center',
    },
    icon:{
        color:'white',
        marginTop: -30,
    },
    faqquestion:{
        fontFamily: 'Barlow Condensed, sans-serif',
        fontWeight: 700,
        fontSize: 15,     
        display: 'flex' ,
        justifyContent: 'space-between',
        transition: 'all 0.4s ease',
        position: 'relative',
    },
    faqquestionopen:{
       marginBottom: 15,
       fontFamily: 'Barlow Condensed, sans-serif',
       fontWeight: 700,
       fontSize: 15,     
       display: 'flex' ,
       justifyContent: 'space-between',
       transition: 'all 0.4s ease',
        position: 'relative',
       
    },
    faqanswer:{
        fontFamily: 'Barlow Condensed, sans-serif',
        marginTop:-20,
        opacity: 0,
        maxHeight: 0,
        overflowY: 'hidden',
        transition: 'all 0.4s ease',
    },
    faqopenanswer:{
        opacity: 1,
        height:'auto',
        maxHeight: '9999px',
        fontFamily: 'Barlow Condensed, sans-serif',
      //  marginTop:-60,
        transition: 'all 0.4s ease',
      
     //   display: 'flex',
     //   paddingBottom: 0,
    },
    faq:{
        margin:15,
        padding: 15,
        marginLeft: 0,
        backgroundColor: 'white',
        borderRadius: 8,
        boxShadow: '0px 0px 10px rgba(0,0,0, 0.2)',
        cursor:'pointer',
    },
    faqs:{ 
        width:'100%',
        maxWidth: 768,
        margin: '0 auto',
        padding: 15,
        paddingLeft: 0,
    },
    faqopen:{
        padding: 15,
        backgroundColor: 'white',
        borderRadius: 8,
        boxShadow: '0px 0px 10px rgba(0,0,0, 0.2)',
        margin:15,
        marginLeft: 0,
    },
    plusicon:{
        fontSize: '1.5rem',
        color: 'white',
        marginTop: -2,
        marginLeft: -0.3,
        fontFamily: 'Comfortaa, cursive',
        fontWeight: 700,
    },
    plusiconcontainer:{
        backgroundColor: '#3d88e4',
        width: 22,
        height: 22,
        borderRadius: 50,
        justifyContent: 'center',
        textAlign: 'center',
    },
    sectionstyle:{
        width: "auto",
        height: "100%",
        backgroundImage: `url(../../images/intro.png) no-repeat center center fixed   `,
        minWidth: "100%",
        minHeight: "100%",
        marginTop: -80,
        backgroundSize: 'cover',
        position: 'relative',
    },
}));


